# Generated by Django 4.2.2 on 2023-06-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
